
services:
  openweb-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openweb-ui
    ports:
      - "8080:8080"
    hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

    volumes:
      open-webui: