services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:main-stable
    ports:
      - 4000:4000

    environment:
      LITELLM_MASTER_KEY: "password"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml

